project_id = "excqwhuvfyoqvcpxtxsa"

[functions.get-saas-from-airtable]
verify_jwt = false

[functions.translate-with-deepl]
verify_jwt = false

[functions.send-diagnostic-email]
verify_jwt = false

[functions.get-ai-recommendations]
verify_jwt = false
