import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.diagnostic': 'Diagnostic IA',
    'nav.catalogue': 'Catalogue SaaS',
    'nav.contact': 'Contact',
    'nav.start_diagnostic': 'Commencer le diagnostic',

    // Hero section
    'hero.badge': 'Transformation Digitale',
    'hero.title': 'Solutio | Diagnostic & comparateur SaaS pour PME',
    'hero.h1_title': 'Diagnostic & comparateur SaaS pour PME',
    'hero.subtitle': 'Diagnostic gratuit + recommandations personnalisées',
    'hero.description': 'Bénéficiez d\'un diagnostic gratuit pour trouver et automatiser vos SaaS. Solutio compare et recommande les meilleurs outils pour PME et freelances.',
    'hero.cta_diagnostic': 'Commencer le diagnostic gratuit',
    'hero.cta_catalog': 'Explorer le catalogue',
    
    // Features section
    'features.intelligent_diagnostic.title': 'Diagnostic Intelligent',
    'features.intelligent_diagnostic.description': 'Notre assistant conversationnel analyse vos processus en 6 questions ciblées pour identifier les tâches à automatiser.',
    'features.personalized_catalog.title': 'Catalogue SaaS Personnalisé',
    'features.personalized_catalog.description': 'Découvrez une sélection de solutions SaaS triées sur le volet, adaptées à votre secteur et vos besoins spécifiques.',
    'features.custom_recommendations.title': 'Recommandations Sur Mesure',
    'features.custom_recommendations.description': 'Recevez des recommandations précises basées sur le potentiel d\'automatisation et la facilité d\'implémentation.',
    
    // Benefits section
    'benefits.save_time.title': 'Gagnez du temps',
    'benefits.save_time.description': 'Jusqu\'à 70% de temps économisé sur vos tâches répétitives',
    'benefits.reduce_costs.title': 'Réduisez vos coûts',
    'benefits.reduce_costs.description': 'ROI moyen de 300% dès la première année',
    'benefits.targeted_solutions.title': 'Solutions ciblées',
    'benefits.targeted_solutions.description': 'Recommandations adaptées à votre secteur et taille d\'entreprise',
    
    // Categories
    'categories.crm': 'CRM & Relation Client',
    'categories.marketing': 'Marketing & Growth',
    'categories.automation': 'Automatisation & No-code',
    'categories.design': 'Création, Design & Multimédia',
    'categories.sales': 'Ventes & E-commerce',
    'categories.project_management': 'Gestion de Projet & Collaboration',
    'categories.productivity': 'Productivité & Outils Bureautiques',
    'categories.security': 'Sécurité & Conformité',
    'categories.finance': 'Finance & Comptabilité',
    'categories.hr': 'Ressources Humaines & Recrutement',
    'categories.education': 'Éducation & Formation',
    'categories.customer_service': 'Service Client & Support',
    'categories.health': 'Santé & Bien-être',
    'categories.industry': 'Industrie & Logistique',
    'categories.development': 'Développement & IT',
    'categories.legal': 'LegalTech & Juridique',
    'categories.count': '{count} outils',
    'categories.title': 'Explorez nos catégories de solutions',
    'categories.subtitle': 'Trouvez les outils parfaits pour votre secteur d\'activité parmi plus de 500 solutions référencées',
    
    // Catalog page
    'catalog.title': 'Catalogue SaaS',
    'catalog.subtitle': 'Découvrez les meilleures solutions pour automatiser votre activité',
    'catalog.search_placeholder': 'Rechercher une solution...',
    'catalog.filter_category': 'Catégorie',
    'catalog.filter_target': 'Cible',
    'catalog.all_categories': 'Toutes les catégories',
    'catalog.all_targets': 'Toutes les cibles',
    'catalog.key_features': 'Fonctionnalités clés',
    'catalog.view_details': 'Voir le détail',
    'catalog.no_results_title': 'Aucune solution trouvée',
    'catalog.no_results_subtitle': 'Essayez de modifier vos critères de recherche',
    'catalog.pagination_previous': 'Précédent',
    'catalog.pagination_next': 'Suivant',
    'catalog.items_per_page': 'Éléments par page',
    'catalog.showing_count': 'Affichage {from}–{to} sur {total}',

    // Contact page
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Besoin d\'aide pour choisir la meilleure solution ? Nos experts sont là pour vous accompagner.',
    'contact.form_title': 'Envoyez-nous un message',
    'contact.name_label': 'Nom complet *',
    'contact.name_placeholder': 'Votre nom',
    'contact.email_label': 'Email *',
    'contact.email_placeholder': 'votre@email.com',
    'contact.company_label': 'Entreprise',
    'contact.company_placeholder': 'Nom de votre entreprise',
    'contact.message_label': 'Message *',
    'contact.message_placeholder': 'Décrivez votre besoin ou votre projet...',
    'contact.submit_button': 'Envoyer le message',
    'contact.success_title': 'Merci pour votre message !',
    'contact.success_message': 'Nous avons bien reçu votre demande et vous répondrons dans les plus brefs délais.',
    'contact.send_another': 'Envoyer un autre message',
    'contact.direct_contact_title': 'Contact direct',
    'contact.email_label_info': 'Email',
    'contact.phone_label': 'Téléphone',
    'contact.hours_label': 'Horaires',
    'contact.hours_value': 'Lun-Ven, 9h-18h',
    'contact.book_call_title': 'Réserver un appel',
    'contact.book_call_subtitle': 'Planifiez un appel de 30 minutes avec un expert pour discuter de vos besoins spécifiques.',
    'contact.book_call_benefit1': 'Analyse gratuite de vos processus',
    'contact.book_call_benefit2': 'Recommandations personnalisées',
    'contact.book_call_benefit3': 'Plan d\'implémentation détaillé',
    'contact.book_call_button': 'Réserver maintenant',
    'contact.faq_title': 'Questions fréquentes',
    'contact.faq_q1': 'Combien coûte un audit ?',
    'contact.faq_a1': 'L\'audit initial est gratuit lors de notre premier appel.',
    'contact.faq_q2': 'Combien de temps pour voir des résultats ?',
    'contact.faq_a2': 'La plupart de nos clients voient des gains de temps dès la première semaine.',
    'contact.faq_q3': 'Vous accompagnez l\'implémentation ?',
    'contact.faq_a3': 'Oui, nous proposons un accompagnement complet de A à Z.',

    // Diagnostic page
    'diagnostic.title': 'Diagnostic IA',
    'diagnostic.subtitle': 'Répondez à 6 questions simples pour découvrir les meilleures solutions d\'automatisation pour votre activité',
    'diagnostic.question_task_title': 'Quelle tâche vous fait perdre du temps ?',
    'diagnostic.question_task_subtitle': 'Décrivez la tâche répétitive qui vous fait perdre le plus de temps',
    'diagnostic.question_task_placeholder': 'Exemple: Saisie manuelle des factures clients, création de rapports mensuels...',
    'diagnostic.question_frequency_title': 'À quelle fréquence effectuez-vous cette tâche ?',
    'diagnostic.question_frequency_subtitle': 'Indiquez le volume et la fréquence',
    'diagnostic.question_frequency_placeholder': 'Exemple: 2 heures par jour, 10 fois par semaine...',
    'diagnostic.question_sector_title': 'Dans quel secteur travaillez-vous ?',
    'diagnostic.question_sector_subtitle': 'Précisez votre domaine d\'activité',
    'diagnostic.question_sector_placeholder': 'Exemple: E-commerce, Consulting, SaaS, Immobilier...',
    'diagnostic.question_tools_title': 'Quels outils utilisez-vous actuellement ?',
    'diagnostic.question_tools_subtitle': 'Listez les logiciels et outils que vous utilisez',
    'diagnostic.question_tools_placeholder': 'Exemple: Excel, Salesforce, Gmail, Slack...',
    'diagnostic.question_deliverable_title': 'Quel est le livrable final attendu ?',
    'diagnostic.question_deliverable_subtitle': 'Décrivez le résultat final de cette tâche',
    'diagnostic.question_deliverable_placeholder': 'Exemple: Rapport PDF, données synchronisées, email personnalisé...',
    'diagnostic.question_constraints_title': 'Y a-t-il des contraintes spécifiques ?',
    'diagnostic.question_constraints_subtitle': 'RGPD, validation manuelle, urgence, budget...',
    'diagnostic.question_constraints_placeholder': 'Exemple: Conformité RGPD, validation obligatoire, budget limité...',
    'diagnostic.question_priority_title': 'Priorité',
    'diagnostic.question_priority_subtitle': 'Sur une échelle de 1 à 5, quelle est la priorité pour vous d\'automatiser cette tâche ?',
    'diagnostic.question_priority_placeholder': '1 = Pas prioritaire, 5 = Très prioritaire',
    'diagnostic.examples_label': 'Exemples populaires :',
    'diagnostic.step_label': 'Étape',
    'diagnostic.progress_completed': 'complété',
    'diagnostic.question_number': 'Question',
    'diagnostic.previous_button': 'Précédent',
    'diagnostic.next_button': 'Suivant',
    'diagnostic.see_recommendations': 'Voir mes recommandations',
    'diagnostic.results_title': 'Diagnostic Terminé !',
    'diagnostic.results_subtitle': 'Voici votre analyse personnalisée et nos recommandations',
    'diagnostic.automation_score': 'Score d\'Automatisation',
    'diagnostic.potential_label': 'Potentiel',
    'diagnostic.time_saved_label': 'Temps économisé',
    'diagnostic.implementation_time': '2-4 semaines',
    'diagnostic.implementation_label': 'Mise en place',
    'diagnostic.roi_label': 'ROI rapide',
    'diagnostic.roi_value': 'Rentabilité',
    'diagnostic.summary_title': 'Résumé de votre diagnostic',
    'diagnostic.task_to_automate': 'TÂCHE À AUTOMATISER',
    'diagnostic.frequency_label_caps': 'FRÉQUENCE',
    'diagnostic.sector_label_caps': 'SECTEUR',
    'diagnostic.current_tools': 'OUTILS ACTUELS',
    'diagnostic.recommendations_title': 'Nos recommandations pour vous',
    'diagnostic.recommendations_subtitle': 'Solutions adaptées à votre profil',
    'diagnostic.ai_recommendations_title': '🎯 Solutions recommandées pour vous',
    'diagnostic.recommended_solution': 'Solution recommandée',
    'diagnostic.high_score': 'Score élevé',
    'diagnostic.receive_email_title': 'Recevoir par email',
    'diagnostic.receive_email_subtitle': 'Recevez ce diagnostic et nos recommandations détaillées',
    'diagnostic.send_report': 'Envoyer le rapport',
    'diagnostic.free_consultation_title': 'Consultation gratuite',
    'diagnostic.free_consultation_subtitle': 'Échangez avec un expert pour affiner votre stratégie',
    'diagnostic.book_slot': 'Réserver un créneau',
    'diagnostic.new_diagnostic': 'Faire un nouveau diagnostic',

    // Home page
    'home.badge': 'Transformation Digitale',
    'home.title': 'Automatisez votre activité avec l\'IA',
    'home.subtitle': 'Découvrez les meilleures solutions SaaS pour automatiser vos tâches répétitives. Diagnostic IA gratuit et recommandations personnalisées en 5 minutes.',
    'home.cta_diagnostic': 'Commencer le diagnostic gratuit',
    'home.cta_catalogue': 'Voir le catalogue',
    'home.free': 'Gratuit',
    'home.minutes': '5 minutes',
    'home.no_commitment': 'Sans engagement',
    'home.how_title': 'Comment Solutio révolutionne votre productivité',
    'home.how_subtitle': 'Une approche en 3 étapes pour identifier, choisir et implémenter les meilleures solutions d\'automatisation',
    'home.feature1_title': 'Diagnostic IA Intelligent',
    'home.feature1_desc': 'Notre assistant conversationnel analyse vos processus en 6 questions ciblées pour identifier les tâches à automatiser.',
    'home.feature2_title': 'Catalogue SaaS Personnalisé',
    'home.feature2_desc': 'Découvrez une sélection de solutions SaaS triées sur le volet, adaptées à votre secteur et vos besoins spécifiques.',
    'home.feature3_title': 'Recommandations Sur Mesure',
    'home.feature3_desc': 'Recevez des recommandations précises basées sur le potentiel d\'automatisation et la facilité d\'implémentation.',
    'home.why_title': 'Pourquoi choisir Solutio ?',
    'home.why_subtitle': 'Nous ne vendons pas de solutions, nous trouvons LA solution qui vous convient parfaitement.',
    'home.benefit1_title': 'Gagnez du temps',
    'home.benefit1_desc': 'Jusqu\'à 70% de temps économisé sur vos tâches répétitives',
    'home.benefit2_title': 'Réduisez vos coûts',
    'home.benefit2_desc': 'ROI moyen de 300% dès la première année',
    'home.benefit3_title': 'Solutions ciblées',
    'home.benefit3_desc': 'Recommandations adaptées à votre secteur et taille d\'entreprise',
    'home.demo_cta': 'Demander une démo personnalisée',
    'home.cta_title': 'Prêt à automatiser votre activité ?',
    'home.cta_subtitle': 'Commencez votre diagnostic gratuit dès maintenant et découvrez comment gagner des heures chaque semaine.',
    'home.diagnostic_5min': 'Diagnostic gratuit en 5 min',
    'home.explore_catalogue': 'Explorer le catalogue',
    'home.solutions_count': 'Solutions référencées',
    'home.satisfaction': 'Clients satisfaits',
    'home.response_time': 'Temps de réponse',

    // Catalogue
    'catalogue.title': 'Catalogue SaaS',
    'catalogue.subtitle': 'Découvrez les meilleures solutions pour automatiser votre activité',
    'catalogue.search_placeholder': 'Rechercher une solution...',
    'catalogue.category_filter': 'Catégorie',
    'catalogue.target_filter': 'Cible',
    'catalogue.all_categories': 'Toutes les catégories',
    'catalogue.all_targets': 'Toutes les cibles',
    'catalogue.solutions_found': 'solution trouvée',
    'catalogue.solutions_found_plural': 'solutions trouvées',
    'catalogue.key_features': 'Fonctionnalités clés :',
    'catalogue.view_detail': 'Voir le détail',
    'catalogue.no_results': 'Aucune solution trouvée',
    'catalogue.modify_search': 'Essayez de modifier vos critères de recherche',

    // Footer
    'footer.tagline': 'Votre partenaire pour la transformation digitale et l\'automatisation.',
    'footer.solutions': 'Solutions',
    'footer.support': 'Support',
    'footer.legal': 'Légal',
    'footer.legal_notice': 'Mentions légales',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'CGU',
    'footer.copyright': '© 2024 Solutio. Tous droits réservés.',

    // SaaS Detail page
    'saasdetail.back_to_catalog': 'Retour au catalogue',
    'saasdetail.main_features': 'Fonctionnalités principales',
    'saasdetail.popular_use_cases': 'Cas d\'usage populaires',
    'saasdetail.advantages': 'Avantages',
    'saasdetail.disadvantages': 'Inconvénients',
    'saasdetail.start_now': 'Commencer maintenant',
    'saasdetail.try_free': 'Essayer gratuitement',
    'saasdetail.visit_website': 'Visiter le site web',
    'saasdetail.ask_advice': 'Demander conseil',
    'saasdetail.pricing': 'Tarification',
    'saasdetail.popular': 'Populaire',
    'saasdetail.per_month': '/mois',
    'saasdetail.ideal_for': 'Idéal pour',
    'saasdetail.automation': 'Automatisation',
    'saasdetail.ease': 'Facilité',
    'saasdetail.from': 'À partir de',

    // Not Found page
    'notfound.title': '404',
    'notfound.message': 'Oops ! Page introuvable',
    'notfound.back_home': 'Retour à l\'accueil',

    // Examples for diagnostic questions
    'diagnostic.examples_task_1': 'Saisie de données clients',
    'diagnostic.examples_task_2': 'Création de rapports',
    'diagnostic.examples_task_3': 'Gestion des emails',
    'diagnostic.examples_task_4': 'Planification de rendez-vous',
    'diagnostic.examples_frequency_1': 'Quotidien',
    'diagnostic.examples_frequency_2': 'Hebdomadaire', 
    'diagnostic.examples_frequency_3': 'Mensuel',
    'diagnostic.examples_frequency_4': 'Ponctuel',
    'diagnostic.examples_sector_1': 'E-commerce',
    'diagnostic.examples_sector_2': 'Consulting',
    'diagnostic.examples_sector_3': 'SaaS',
    'diagnostic.examples_sector_4': 'Finance',
    'diagnostic.examples_sector_5': 'Marketing',
    'diagnostic.examples_sector_6': 'RH',
    'diagnostic.examples_tools_1': 'Excel',
    'diagnostic.examples_tools_2': 'Google Sheets',
    'diagnostic.examples_tools_3': 'CRM',
    'diagnostic.examples_tools_4': 'ERP',
    'diagnostic.examples_tools_5': 'Email',
    'diagnostic.examples_tools_6': 'Aucun outil',
    'diagnostic.examples_deliverable_1': 'Gagner du temps',
    'diagnostic.examples_deliverable_2': 'Réduire les erreurs',
    'diagnostic.examples_deliverable_3': 'Améliorer la productivité',
    'diagnostic.examples_deliverable_4': 'Simplifier les processus',
    'diagnostic.examples_constraints_1': 'Budget < 100€/mois',
    'diagnostic.examples_constraints_2': 'Intégration ERP obligatoire',
    'diagnostic.examples_constraints_3': 'Conformité RGPD',
    'diagnostic.examples_constraints_4': 'Hébergement France',
    'diagnostic.examples_constraints_5': 'Aucune contrainte',

    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.close': 'Fermer',
    'common.confirm': 'Confirmer'
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.diagnostic': 'AI Diagnostic',
    'nav.catalogue': 'SaaS Catalogue',
    'nav.contact': 'Contact',
    'nav.start_diagnostic': 'Start diagnostic',

    // Hero section
    'hero.badge': 'Digital Transformation',
    'hero.title': 'Find the best SaaS solution to automate your business',
    'hero.subtitle': 'Free diagnostic + personalized recommendations',
    'hero.description': 'Solutio also helps you implement effective tools in your business processes.',
    'hero.cta_diagnostic': 'Start free diagnostic',
    'hero.cta_catalog': 'Explore catalog',
    
    // Features section
    'features.intelligent_diagnostic.title': 'Intelligent Diagnostic',
    'features.intelligent_diagnostic.description': 'Our conversational assistant analyzes your processes with 6 targeted questions to identify tasks to automate.',
    'features.personalized_catalog.title': 'Personalized SaaS Catalog',
    'features.personalized_catalog.description': 'Discover a curated selection of SaaS solutions, tailored to your industry and specific needs.',
    'features.custom_recommendations.title': 'Custom Recommendations',
    'features.custom_recommendations.description': 'Receive precise recommendations based on automation potential and implementation ease.',
    
    // Benefits section
    'benefits.save_time.title': 'Save time',
    'benefits.save_time.description': 'Up to 70% time saved on your repetitive tasks',
    'benefits.reduce_costs.title': 'Reduce costs',
    'benefits.reduce_costs.description': 'Average ROI of 300% from the first year',
    'benefits.targeted_solutions.title': 'Targeted solutions',
    'benefits.targeted_solutions.description': 'Recommendations adapted to your industry and company size',
    
    // Categories
    'categories.crm': 'CRM & Customer Relations',
    'categories.marketing': 'Marketing & Growth',
    'categories.automation': 'Automation & No-code',
    'categories.design': 'Creation, Design & Multimedia',
    'categories.sales': 'Sales & E-commerce',
    'categories.project_management': 'Project Management & Collaboration',
    'categories.productivity': 'Productivity & Office Tools',
    'categories.security': 'Security & Compliance',
    'categories.finance': 'Finance & Accounting',
    'categories.hr': 'Human Resources & Recruitment',
    'categories.education': 'Education & Training',
    'categories.customer_service': 'Customer Service & Support',
    'categories.health': 'Health & Wellness',
    'categories.industry': 'Industry & Logistics',
    'categories.development': 'Development & IT',
    'categories.legal': 'LegalTech & Legal',
    'categories.count': '{count} tools',
    'categories.title': 'Explore our solution categories',
    'categories.subtitle': 'Find the perfect tools for your industry among more than 500 referenced solutions',
    
    // Catalog page
    'catalog.title': 'SaaS Catalog',
    'catalog.subtitle': 'Discover the best solutions to automate your business',
    'catalog.search_placeholder': 'Search for a solution...',
    'catalog.filter_category': 'Category',
    'catalog.filter_target': 'Target',
    'catalog.all_categories': 'All categories',
    'catalog.all_targets': 'All targets',
    'catalog.key_features': 'Key features',
    'catalog.view_details': 'View details',
    'catalog.no_results_title': 'No solutions found',
    'catalog.no_results_subtitle': 'Try modifying your search criteria',

    'catalog.pagination_previous': 'Previous',
    'catalog.pagination_next': 'Next',
    'catalog.items_per_page': 'Items per page',
    'catalog.showing_count': 'Showing {from}–{to} of {total}',

    // Contact page
    'contact.title': 'Contact us',
    'contact.subtitle': 'Need help choosing the best solution? Our experts are here to help you.',
    'contact.form_title': 'Send us a message',
    'contact.name_label': 'Full name *',
    'contact.name_placeholder': 'Your name',
    'contact.email_label': 'Email *',
    'contact.email_placeholder': 'your@email.com',
    'contact.company_label': 'Company',
    'contact.company_placeholder': 'Your company name',
    'contact.message_label': 'Message *',
    'contact.message_placeholder': 'Describe your need or project...',
    'contact.submit_button': 'Send message',
    'contact.success_title': 'Thank you for your message!',
    'contact.success_message': 'We have received your request and will respond as soon as possible.',
    'contact.send_another': 'Send another message',
    'contact.direct_contact_title': 'Direct contact',
    'contact.email_label_info': 'Email',
    'contact.phone_label': 'Phone',
    'contact.hours_label': 'Hours',
    'contact.hours_value': 'Mon-Fri, 9am-6pm',
    'contact.book_call_title': 'Book a call',
    'contact.book_call_subtitle': 'Schedule a 30-minute call with an expert to discuss your specific needs.',
    'contact.book_call_benefit1': 'Free process analysis',
    'contact.book_call_benefit2': 'Personalized recommendations',
    'contact.book_call_benefit3': 'Detailed implementation plan',
    'contact.book_call_button': 'Book now',
    'contact.faq_title': 'Frequently asked questions',
    'contact.faq_q1': 'How much does an audit cost?',
    'contact.faq_a1': 'The initial audit is free during our first call.',
    'contact.faq_q2': 'How long to see results?',
    'contact.faq_a2': 'Most of our clients see time savings from the first week.',
    'contact.faq_q3': 'Do you support implementation?',
    'contact.faq_a3': 'Yes, we offer complete end-to-end support.',

    // Diagnostic page
    'diagnostic.title': 'AI Diagnostic',
    'diagnostic.subtitle': 'Answer 6 simple questions to discover the best automation solutions for your business',
    'diagnostic.question_task_title': 'What task is wasting your time?',
    'diagnostic.question_task_subtitle': 'Describe the repetitive task that wastes the most time',
    'diagnostic.question_task_placeholder': 'Example: Manual entry of customer invoices, monthly report creation...',
    'diagnostic.question_frequency_title': 'How often do you perform this task?',
    'diagnostic.question_frequency_subtitle': 'Indicate the volume and frequency',
    'diagnostic.question_frequency_placeholder': 'Example: 2 hours per day, 10 times per week...',
    'diagnostic.question_sector_title': 'What sector do you work in?',
    'diagnostic.question_sector_subtitle': 'Specify your business domain',
    'diagnostic.question_sector_placeholder': 'Example: E-commerce, Consulting, SaaS, Real Estate...',
    'diagnostic.question_tools_title': 'What tools do you currently use?',
    'diagnostic.question_tools_subtitle': 'List the software and tools you use',
    'diagnostic.question_tools_placeholder': 'Example: Excel, Salesforce, Gmail, Slack...',
    'diagnostic.question_deliverable_title': 'What is the expected final deliverable?',
    'diagnostic.question_deliverable_subtitle': 'Describe the final result of this task',
    'diagnostic.question_deliverable_placeholder': 'Example: PDF report, synchronized data, personalized email...',
    'diagnostic.question_constraints_title': 'Are there specific constraints?',
    'diagnostic.question_constraints_subtitle': 'GDPR, manual validation, urgency, budget...',
    'diagnostic.question_constraints_placeholder': 'Example: GDPR compliance, mandatory validation, limited budget...',
    'diagnostic.question_priority_title': 'Priority',
    'diagnostic.question_priority_subtitle': 'On a scale of 1 to 5, what is the priority for you to automate this task?',
    'diagnostic.question_priority_placeholder': '1 = Not priority, 5 = Very priority',
    'diagnostic.examples_label': 'Popular examples:',
    'diagnostic.step_label': 'Step',
    'diagnostic.progress_completed': 'completed',
    'diagnostic.question_number': 'Question',
    'diagnostic.previous_button': 'Previous',
    'diagnostic.next_button': 'Next',
    'diagnostic.see_recommendations': 'See my recommendations',
    'diagnostic.results_title': 'Diagnostic Complete!',
    'diagnostic.results_subtitle': 'Here is your personalized analysis and our recommendations',
    'diagnostic.automation_score': 'Automation Score',
    'diagnostic.potential_label': 'Potential',
    'diagnostic.time_saved_label': 'Time saved',
    'diagnostic.implementation_time': '2-4 weeks',
    'diagnostic.implementation_label': 'Implementation',
    'diagnostic.roi_label': 'Fast ROI',
    'diagnostic.roi_value': 'Profitability',
    'diagnostic.summary_title': 'Summary of your diagnostic',
    'diagnostic.task_to_automate': 'TASK TO AUTOMATE',
    'diagnostic.frequency_label_caps': 'FREQUENCY',
    'diagnostic.sector_label_caps': 'SECTOR',
    'diagnostic.current_tools': 'CURRENT TOOLS',
    'diagnostic.recommendations_title': 'Our recommendations for you',
    'diagnostic.recommendations_subtitle': 'Solutions adapted to your profile',
    'diagnostic.ai_recommendations_title': '🎯 Recommended Solutions for You',
    'diagnostic.recommended_solution': 'Recommended solution',
    'diagnostic.high_score': 'High score',
    'diagnostic.receive_email_title': 'Receive by email',
    'diagnostic.receive_email_subtitle': 'Get this diagnostic and our detailed recommendations',
    'diagnostic.send_report': 'Send report',
    'diagnostic.free_consultation_title': 'Free consultation',
    'diagnostic.free_consultation_subtitle': 'Talk with an expert to refine your strategy',
    'diagnostic.book_slot': 'Book a slot',
    'diagnostic.new_diagnostic': 'Start new diagnostic',

    // Home page
    'home.badge': 'Digital Transformation',
    'home.title': 'Automate your business with AI',
    'home.subtitle': 'Discover the best SaaS solutions to automate your repetitive tasks. Free AI diagnostic and personalized recommendations in 5 minutes.',
    'home.cta_diagnostic': 'Start free diagnostic',
    'home.cta_catalogue': 'View catalogue',
    'home.free': 'Free',
    'home.minutes': '5 minutes',
    'home.no_commitment': 'No commitment',
    'home.how_title': 'How Solutio revolutionizes your productivity',
    'home.how_subtitle': 'A 3-step approach to identify, choose and implement the best automation solutions',
    'home.feature1_title': 'Intelligent AI Diagnostic',
    'home.feature1_desc': 'Our conversational assistant analyzes your processes with 6 targeted questions to identify tasks to automate.',
    'home.feature2_title': 'Personalized SaaS Catalogue',
    'home.feature2_desc': 'Discover a curated selection of SaaS solutions, tailored to your industry and specific needs.',
    'home.feature3_title': 'Custom Recommendations',
    'home.feature3_desc': 'Receive precise recommendations based on automation potential and implementation ease.',
    'home.why_title': 'Why choose Solutio?',
    'home.why_subtitle': 'We don\'t sell solutions, we find THE solution that fits you perfectly.',
    'home.benefit1_title': 'Save time',
    'home.benefit1_desc': 'Up to 70% time saved on your repetitive tasks',
    'home.benefit2_title': 'Reduce costs',
    'home.benefit2_desc': 'Average ROI of 300% from the first year',
    'home.benefit3_title': 'Targeted solutions',
    'home.benefit3_desc': 'Recommendations adapted to your industry and company size',
    'home.demo_cta': 'Request a personalized demo',
    'home.cta_title': 'Ready to automate your business?',
    'home.cta_subtitle': 'Start your free diagnostic now and discover how to save hours every week.',
    'home.diagnostic_5min': 'Free 5-min diagnostic',
    'home.explore_catalogue': 'Explore catalogue',
    'home.solutions_count': 'Referenced solutions',
    'home.satisfaction': 'Satisfied customers',
    'home.response_time': 'Response time',

    // Catalogue
    'catalogue.title': 'SaaS Catalogue',
    'catalogue.subtitle': 'Discover the best solutions to automate your business',
    'catalogue.search_placeholder': 'Search for a solution...',
    'catalogue.category_filter': 'Category',
    'catalogue.target_filter': 'Target',
    'catalogue.all_categories': 'All categories',
    'catalogue.all_targets': 'All targets',
    'catalogue.solutions_found': 'solution found',
    'catalogue.solutions_found_plural': 'solutions found',
    'catalogue.key_features': 'Key features:',
    'catalogue.view_detail': 'View details',
    'catalogue.no_results': 'No solutions found',
    'catalogue.modify_search': 'Try modifying your search criteria',

    // Footer
    'footer.tagline': 'Your partner for digital transformation and automation.',
    'footer.solutions': 'Solutions',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.legal_notice': 'Legal notice',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.copyright': '© 2024 Solutio. All rights reserved.',

    // SaaS Detail page
    'saasdetail.back_to_catalog': 'Back to catalog',
    'saasdetail.main_features': 'Main features',
    'saasdetail.popular_use_cases': 'Popular use cases',
    'saasdetail.advantages': 'Advantages',
    'saasdetail.disadvantages': 'Disadvantages',
    'saasdetail.start_now': 'Start now',
    'saasdetail.try_free': 'Try for free',
    'saasdetail.visit_website': 'Visit website',
    'saasdetail.ask_advice': 'Ask for advice',
    'saasdetail.pricing': 'Pricing',
    'saasdetail.popular': 'Popular',
    'saasdetail.per_month': '/month',
    'saasdetail.ideal_for': 'Ideal for',
    'saasdetail.automation': 'Automation',
    'saasdetail.ease': 'Ease',
    'saasdetail.from': 'From',

    // Not Found page
    'notfound.title': '404',
    'notfound.message': 'Oops! Page not found',
    'notfound.back_home': 'Return to Home',

    // Examples for diagnostic questions
    'diagnostic.examples_task_1': 'Client data entry',
    'diagnostic.examples_task_2': 'Report creation',
    'diagnostic.examples_task_3': 'Email management',
    'diagnostic.examples_task_4': 'Appointment scheduling',
    'diagnostic.examples_frequency_1': 'Daily',
    'diagnostic.examples_frequency_2': 'Weekly',
    'diagnostic.examples_frequency_3': 'Monthly',
    'diagnostic.examples_frequency_4': 'Occasional',
    'diagnostic.examples_sector_1': 'E-commerce',
    'diagnostic.examples_sector_2': 'Consulting',
    'diagnostic.examples_sector_3': 'SaaS',
    'diagnostic.examples_sector_4': 'Finance',
    'diagnostic.examples_sector_5': 'Marketing',
    'diagnostic.examples_sector_6': 'HR',
    'diagnostic.examples_tools_1': 'Excel',
    'diagnostic.examples_tools_2': 'Google Sheets',
    'diagnostic.examples_tools_3': 'CRM',
    'diagnostic.examples_tools_4': 'ERP',
    'diagnostic.examples_tools_5': 'Email',
    'diagnostic.examples_tools_6': 'No tool',
    'diagnostic.examples_deliverable_1': 'Save time',
    'diagnostic.examples_deliverable_2': 'Reduce errors',
    'diagnostic.examples_deliverable_3': 'Improve productivity',
    'diagnostic.examples_deliverable_4': 'Simplify processes',
    'diagnostic.examples_constraints_1': 'Budget < $100/month',
    'diagnostic.examples_constraints_2': 'ERP integration required',
    'diagnostic.examples_constraints_3': 'GDPR compliance',
    'diagnostic.examples_constraints_4': 'French hosting',
    'diagnostic.examples_constraints_5': 'No constraints',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.close': 'Close',
    'common.confirm': 'Confirm'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language][key] || key;
    
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, params[param]);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};