import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.diagnostic': 'Diagnostic',
    'nav.cartographie': 'Cartographie',
    'nav.contact': 'Contact',
    'nav.start_diagnostic': 'Scanner gratuitement',
    'nav.start_scan': 'Scanner gratuitement',
    'nav.book_meeting': 'Réserver un échange',
    'nav.outils': 'Outils',
    'nav.realisations': 'Realisations',
    'nav.accompagnement': 'Accompagnement',
    'nav.conviction': 'Notre conviction',

    // Hero section
    'hero.badge': 'Conseil & Transformation Digitale',
    'hero.title': 'Solutio | Conseil en transformation digitale & cartographie organisationnelle',
    'hero.h1_title': 'Transformez votre organisation avec l\'IA',
    'hero.subtitle': 'Cartographie organisationnelle, analyse IA et accompagnement sur mesure',
    'hero.description': 'Solutio vous accompagne dans votre transformation digitale : scan gratuit en 3 minutes, cartographie complète de vos processus et plan d\'action concret pour gagner en efficacité.',
    'hero.cta_diagnostic': 'Scanner mon organisation',
    'hero.cta_scan': 'Scanner mon organisation',
    'hero.cta_cartographie': 'Cartographie complète',
    'hero.cta_expert': 'Parler à un expert',
    'home.scan_free_3min': 'Scan gratuit en 3 min',

    // Trust indicators
    'home.free': 'Gratuit',
    'home.minutes': '3 minutes',
    'home.no_commitment': 'Sans engagement',

    // Problem section
    'problem.title': 'Les défis de la transformation digitale',
    'problem.pain1': 'Vos processus internes sont opaques et difficiles à optimiser',
    'problem.pain2': 'Vous perdez du temps sur des tâches à faible valeur ajoutée',
    'problem.pain3': 'Vos équipes manquent de visibilité sur les priorités',
    'problem.pain4': 'Vous ne savez pas par où commencer votre transformation',
    'problem.stat': '70% des projets de transformation digitale échouent par manque de diagnostic préalable',
    'problem.stat_source': 'Étude McKinsey 2024',
    'problem.transition': 'Un diagnostic structuré change tout.',

    // Services section (NEW - replaces Categories)
    'services.title': 'Notre offre',
    'services.subtitle': 'Un accompagnement complet pour réussir votre transformation digitale',
    'services.diagnostic.title': 'Diagnostic IA',
    'services.diagnostic.description': 'Évaluation rapide de votre maturité digitale et identification des axes d\'amélioration prioritaires.',
    'services.diagnostic.cta': 'Lancer le diagnostic',
    'services.cartographie.title': 'Cartographie organisationnelle',
    'services.cartographie.description': '10 packs d\'analyse couvrant tous vos processus : RH, finance, commercial, IT et plus encore.',
    'services.cartographie.cta': 'Découvrir les packs',
    'services.conseil.title': 'Conseil stratégique',
    'services.conseil.description': 'Recommandations personnalisées et plan d\'action concret pour chaque axe de transformation identifié.',
    'services.conseil.cta': 'En savoir plus',
    'services.accompagnement.title': 'Accompagnement',
    'services.accompagnement.description': 'Suivi de la mise en œuvre, formation des équipes et mesure des résultats sur la durée.',
    'services.accompagnement.cta': 'Nous contacter',

    // Method section
    'method.title': 'Notre méthode en 3 étapes',
    'method.subtitle': 'Un parcours structuré pour transformer votre organisation efficacement',
    'method.step1.title': 'Diagnostic IA rapide',
    'method.step1.description': '5 questions ciblées pour évaluer votre maturité digitale et identifier vos priorités. Gratuit et sans engagement.',
    'method.step2.title': 'Cartographie organisationnelle',
    'method.step2.description': '10 packs d\'analyse approfondis couvrant tous les domaines de votre organisation, enrichis par l\'IA.',
    'method.step3.title': 'Plan d\'action & accompagnement',
    'method.step3.description': 'Recommandations concrètes, feuille de route priorisée et accompagnement dans la mise en œuvre.',

    // Proof section
    'proof.title': 'Pourquoi investir dans la transformation digitale',
    'proof.stat1': '-30%',
    'proof.stat1_detail': 'de coûts opérationnels grâce à l\'optimisation des processus',
    'proof.stat1_source': 'McKinsey 2024',
    'proof.stat2': '+40%',
    'proof.stat2_detail': 'de productivité avec des processus bien cartographiés',
    'proof.stat2_source': 'Forrester Research',
    'proof.stat3': '3x',
    'proof.stat3_detail': 'plus de chances de réussir sa transformation avec un diagnostic préalable',
    'proof.stat3_message': 'Commencez par le diagnostic',
    'proof.urgency': 'Chaque mois sans diagnostic clair, c\'est du temps et des ressources mal orientés',
    'proof.cta': 'Commencer mon diagnostic gratuit',

    // Benefits section
    'benefits.title': 'Ce que Solutio vous apporte',
    'benefits.subtitle': 'Une approche concrète et mesurable de la transformation digitale.',
    'benefits.time.title': 'Clarté immédiate',
    'benefits.time.description': 'En 5 minutes, obtenez un état des lieux clair de votre maturité digitale et vos axes prioritaires.',
    'benefits.costs.title': 'Réduction des coûts',
    'benefits.costs.description': 'Identifiez les processus à optimiser en priorité pour un impact financier rapide.',
    'benefits.clarity.title': 'Vision 360° de votre organisation',
    'benefits.clarity.description': 'La cartographie révèle les interdépendances et les leviers de transformation.',
    'benefits.expert.title': 'Accompagnement expert',
    'benefits.expert.description': 'Un plan d\'action sur mesure et un suivi pour garantir des résultats concrets.',

    // CTA section
    'home.cta_title': 'Prêt à transformer votre organisation ?',
    'home.cta_subtitle': 'Le diagnostic est gratuit, les résultats sont immédiats, l\'impact est mesurable.',
    'home.cta_additional': 'Commencez par un diagnostic IA de 5 minutes ou explorez notre cartographie organisationnelle complète.',
    'home.diagnostic_5min': 'Diagnostic gratuit (5 min)',
    'home.expert_cta': 'Découvrir la cartographie',
    'home.solutions_count': 'entreprises accompagnées',
    'home.satisfaction': 'de satisfaction client',
    'home.response_time': 'pour obtenir votre diagnostic personnalisé',

    // Testimonials
    'testimonial.1.quote': 'Le diagnostic nous a permis de prioriser nos chantiers de transformation. En 3 mois, nous avons gagné 15h/semaine.',
    'testimonial.1.author': 'Marie D.',
    'testimonial.1.role': 'Directrice des opérations',
    'testimonial.1.company': 'PME Services',
    'testimonial.2.quote': 'La cartographie organisationnelle a révélé des inefficacités qu\'on ne soupçonnait pas. Un vrai game-changer.',
    'testimonial.2.author': 'Thomas L.',
    'testimonial.2.role': 'CEO',
    'testimonial.2.company': 'TechStart',

    // Contact page
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Besoin d\'accompagnement pour votre transformation digitale ? Nos experts sont là pour vous guider.',
    'contact.form_title': 'Envoyez-nous un message',
    'contact.name_label': 'Nom complet *',
    'contact.name_placeholder': 'Votre nom',
    'contact.email_label': 'Email *',
    'contact.email_placeholder': 'votre@email.com',
    'contact.company_label': 'Entreprise',
    'contact.company_placeholder': 'Nom de votre entreprise',
    'contact.project_type_label': 'Type de projet',
    'contact.project_type_placeholder': 'Sélectionnez...',
    'contact.project_type_brainstorm': 'Session de brainstorming — Explorer une idée ou un besoin',
    'contact.project_type_simple': 'Site web ou outil simple — Besoin cadré, livraison rapide',
    'contact.project_type_big': 'Projet structurant — Système complet, plusieurs modules',
    'contact.project_type_other': 'Autre — Je ne sais pas encore',
    'contact.message_label': 'Message *',
    'contact.message_placeholder': 'Décrivez votre besoin ou votre projet de transformation...',
    'contact.submit_button': 'Envoyer le message',
    'contact.success_title': 'Merci pour votre message !',
    'contact.success_message': 'Nous avons bien reçu votre demande et vous répondrons dans les plus brefs délais.',
    'contact.send_another': 'Envoyer un autre message',
    'contact.direct_contact_title': 'Contact direct',
    'contact.email_label_info': 'Email',
    'contact.phone_label': 'Téléphone',
    'contact.hours_label': 'Horaires',
    'contact.hours_value': 'Lun-Ven, 9h-18h',
    'contact.book_call_title': 'Réserver un appel',
    'contact.book_call_subtitle': 'Planifiez un appel de 30 minutes avec un expert pour discuter de vos besoins.',
    'contact.book_call_benefit1': 'Diagnostic gratuit de vos processus',
    'contact.book_call_benefit2': 'Recommandations personnalisées',
    'contact.book_call_benefit3': 'Plan d\'action détaillé',
    'contact.book_call_button': 'Réserver maintenant',
    'contact.faq_title': 'Questions fréquentes',
    'contact.faq_q1': 'Combien coûte un diagnostic ?',
    'contact.faq_a1': 'Le diagnostic IA en ligne est entièrement gratuit. L\'accompagnement personnalisé est sur devis.',
    'contact.faq_q2': 'Combien de temps pour voir des résultats ?',
    'contact.faq_a2': 'Le diagnostic donne des résultats immédiats. Les premiers gains concrets apparaissent sous 4 à 8 semaines.',
    'contact.faq_q3': 'Vous accompagnez la mise en œuvre ?',
    'contact.faq_a3': 'Oui, nous proposons un accompagnement complet : de la stratégie à l\'exécution.',

    // Diagnostic page (simplified 5-step version)
    'diagnostic.title': 'Diagnostic de maturité digitale',
    'diagnostic.subtitle': 'Répondez à 5 questions pour évaluer votre organisation et recevoir des recommandations personnalisées',
    'diagnostic.question_company_title': 'Quelle est la taille de votre entreprise ?',
    'diagnostic.question_company_subtitle': 'Nombre de collaborateurs',
    'diagnostic.question_sector_title': 'Quel est votre secteur d\'activité ?',
    'diagnostic.question_sector_subtitle': 'Votre domaine principal',
    'diagnostic.question_challenges_title': 'Quels sont vos principaux défis ?',
    'diagnostic.question_challenges_subtitle': 'Sélectionnez ou décrivez vos problématiques actuelles',
    'diagnostic.question_maturity_title': 'Quel est votre niveau de digitalisation actuel ?',
    'diagnostic.question_maturity_subtitle': 'Évaluez votre situation actuelle',
    'diagnostic.question_priorities_title': 'Quelles sont vos priorités de transformation ?',
    'diagnostic.question_priorities_subtitle': 'Ce que vous souhaitez améliorer en priorité',

    'diagnostic.examples_company_1': '1-10 personnes',
    'diagnostic.examples_company_2': '11-50 personnes',
    'diagnostic.examples_company_3': '51-200 personnes',
    'diagnostic.examples_company_4': '200+ personnes',
    'diagnostic.examples_sector_1': 'Services',
    'diagnostic.examples_sector_2': 'Commerce',
    'diagnostic.examples_sector_3': 'Industrie',
    'diagnostic.examples_sector_4': 'Tech / SaaS',
    'diagnostic.examples_sector_5': 'Santé',
    'diagnostic.examples_sector_6': 'Finance',
    'diagnostic.examples_challenges_1': 'Processus manuels chronophages',
    'diagnostic.examples_challenges_2': 'Manque de visibilité / reporting',
    'diagnostic.examples_challenges_3': 'Communication inter-équipes',
    'diagnostic.examples_challenges_4': 'Gestion documentaire désorganisée',
    'diagnostic.examples_challenges_5': 'Outils non connectés',
    'diagnostic.examples_maturity_1': 'Très peu digitalisé (Excel, papier)',
    'diagnostic.examples_maturity_2': 'Quelques outils isolés',
    'diagnostic.examples_maturity_3': 'Outils connectés mais sous-utilisés',
    'diagnostic.examples_maturity_4': 'Bonne digitalisation, besoin d\'optimiser',
    'diagnostic.examples_priorities_1': 'Automatiser les tâches répétitives',
    'diagnostic.examples_priorities_2': 'Améliorer la collaboration',
    'diagnostic.examples_priorities_3': 'Optimiser les processus métier',
    'diagnostic.examples_priorities_4': 'Mieux piloter avec des données',
    'diagnostic.examples_priorities_5': 'Réduire les coûts opérationnels',

    'diagnostic.examples_label': 'Options :',
    'diagnostic.step_label': 'Étape',
    'diagnostic.progress_completed': 'complété',
    'diagnostic.question_number': 'Question',
    'diagnostic.previous_button': 'Précédent',
    'diagnostic.next_button': 'Suivant',
    'diagnostic.see_recommendations': 'Voir mon diagnostic',
    'diagnostic.results_title': 'Votre diagnostic de maturité digitale',
    'diagnostic.results_subtitle': 'Voici votre score et nos recommandations personnalisées',
    'diagnostic.maturity_score': 'Score de maturité',
    'diagnostic.potential_label': 'Potentiel',
    'diagnostic.time_saved_label': 'Gain estimé',
    'diagnostic.implementation_time': '4-8 semaines',
    'diagnostic.implementation_label': 'Premiers résultats',
    'diagnostic.roi_label': 'ROI rapide',
    'diagnostic.roi_value': 'Mesurable',
    'diagnostic.summary_title': 'Résumé de votre diagnostic',
    'diagnostic.company_size_caps': 'TAILLE',
    'diagnostic.sector_label_caps': 'SECTEUR',
    'diagnostic.challenges_caps': 'DÉFIS',
    'diagnostic.maturity_caps': 'MATURITÉ',
    'diagnostic.recommendations_title': 'Nos recommandations',
    'diagnostic.recommendations_subtitle': 'Actions prioritaires pour votre organisation',
    'diagnostic.cta_cartographie_title': 'Aller plus loin avec la cartographie',
    'diagnostic.cta_cartographie_subtitle': 'Obtenez une analyse détaillée de chaque domaine de votre organisation avec nos 10 packs d\'analyse.',
    'diagnostic.cta_cartographie_button': 'Découvrir la cartographie',
    'diagnostic.receive_email_title': 'Recevoir par email',
    'diagnostic.receive_email_subtitle': 'Recevez ce diagnostic et nos recommandations détaillées',
    'diagnostic.send_report': 'Envoyer le rapport',
    'diagnostic.free_consultation_title': 'Consultation gratuite',
    'diagnostic.free_consultation_subtitle': 'Échangez avec un expert pour affiner votre stratégie',
    'diagnostic.book_slot': 'Réserver un créneau',
    'diagnostic.new_diagnostic': 'Refaire le diagnostic',

    // ── NEW HOMEPAGE ──
    // Hero
    'home.badge': 'Conseil & Transformation Digitale',
    'home.hero_line1': 'Vos équipes sont excellentes.',
    'home.hero_line2': 'Leur environnement devrait l\'être aussi.',
    'home.hero_sub': 'Solutio existe pour que les professionnels puissent se concentrer sur ce qui leur rapporte — pas sur ce qui leur coûte.',
    'home.hero_btn_tools': 'Voir nos outils',
    'home.hero_btn_work': 'Travailler avec nous',
    'home.hero_pill1': '2 outils en production',
    'home.hero_pill2': 'Systèmes sur mesure',
    'home.hero_pill3': 'Accompagnement conseil',
    'home.hero_scroll': 'Défiler',

    // Outils
    'home.outils_label': 'Nos produits',
    'home.outils_title': 'Des outils construits pour des vrais problèmes.',
    'home.outils_title_accent': 'Pas des features génériques.',
    'home.outils_sub': 'Chaque produit naît d\'un manque identifié sur le terrain. La roadmap grandit avec les besoins.',
    'home.carto_title': 'Cartographie Orga',
    'home.carto_desc': 'Évaluez la maturité de vos processus, outils et équipes. Identifiez les irritants et générez un plan d\'optimisation actionnable.',
    'home.carto_f1': 'Diagnostic gratuit en 10 packs',
    'home.carto_f2': 'Radar de maturité par domaine',
    'home.carto_f3': 'Quick wins immédiats',
    'home.carto_f4': 'Plan d\'action priorisé par IA',
    'home.carto_btn': 'Découvrir l\'outil',
    'home.carto_badge': 'Disponible',
    'home.lead_title': 'Lead Scraper',
    'home.lead_desc': 'Génération de leads ultra-ciblés pour entrepreneurs, freelances et TPE. Trouvez vos cibles de niche sans les outils enterprise.',
    'home.lead_f1': 'Scraping de sources pertinentes',
    'home.lead_f2': 'Filtrage par critères niche',
    'home.lead_f3': 'Export propre et actionnable',
    'home.lead_f4': 'Sans abonnement enterprise',
    'home.lead_btn': 'Rejoindre la liste d\'attente',
    'home.lead_badge': 'Bientôt',
    'home.next_title': 'Prochain outil',
    'home.next_desc': 'En cours d\'identification. La roadmap est construite à partir des retours terrain et des besoins récurrents chez nos clients.',
    'home.next_sub': 'Vous avez un besoin récurrent que aucun outil ne couvre correctement ? On veut l\'entendre.',
    'home.next_btn': 'Partager un besoin',

    // Réalisations
    'home.real_label': 'Développement sur mesure',
    'home.real_title': 'Quand aucun outil existant ne correspond exactement',
    'home.real_title_accent': 'à votre façon de travailler.',
    'home.real_sub': 'On conçoit et développe des systèmes applicatifs taillés pour votre organisation — pas un outil standard qu\'on vous demande d\'adapter. Architecture, intégrations, interfaces : tout est pensé pour vos équipes.',
    'home.real1_sector': 'Cabinet de conseil',
    'home.real1_tag1': 'Suivi de mission',
    'home.real1_tag2': 'Portail consultants',
    'home.real1_tag3': 'Reporting automatisé',
    'home.real1_metric': '5 outils métier + 1 plateforme de gestion',
    'home.real1_metric_label': 'au lieu d\'un pilotage 100% manuel',
    'home.real1_before': '25+ consultants, tout géré manuellement. Saisies redondantes, coordination dispersée, aucune vision consolidée. Le temps administratif l\'emportait sur le terrain.',
    'home.real1_after': 'Une plateforme sur mesure, 5 outils métier intégrés et une plateforme de gestion centralisée. Missions, activité, livrables — tout en un seul endroit. La structure tourne de façon autonome, sans intervention manuelle.',
    'home.real2_sector': 'Agence marketing d\'affiliation',
    'home.real2_tag1': 'SaaS Platform',
    'home.real2_tag2': 'Automation',
    'home.real2_tag3': 'Multi-clients',
    'home.real2_metric': '-85%',
    'home.real2_metric_label': 'temps opérationnel',
    'home.real2_before': 'Gestion manuelle de 6 clients d\'affiliation. Rapports hebdomadaires créés à la main dans Excel, extraction de données depuis 3 networks (Rakuten, Impact, Awin), briefs dispersés entre emails et Google Docs. 20 heures par semaine uniquement sur le reporting.',
    'home.real2_after': 'Plateforme SaaS full-stack : import automatique multi-network, dashboard analytics temps réel, rapports hebdomadaires générés par IA chaque lundi, intégration ClickUp. 3 heures par semaine au lieu de 20. Scalabilité de 6 à 50+ clients.',
    'home.real_before_label': 'Situation initiale',
    'home.real_after_label': 'Résultat',

    // Accompagnement
    'home.acc_label': 'Transformation digitale',
    'home.acc_title': 'Ce n\'est pas qu\'une question d\'outils.',
    'home.acc_title_accent': 'C\'est une question de comment votre organisation fonctionne vraiment.',
    'home.acc_p1': 'Diagnostiquer, prioriser, implémenter, former. On accompagne les PME de la cartographie de leurs dysfonctionnements jusqu\'à la mise en production des solutions.',
    'home.acc_p2': 'On intervient là où ça bloque vraiment — pas là où c\'est confortable à adresser. Et on repart quand c\'est en marche, pas quand la mission est terminée sur le papier.',
    'home.acc_btn1': 'Parler de mon projet',
    'home.acc_btn2': 'Découvrir nos outils',
    'home.acc_limit': 'Disponibilité limitée — quelques entreprises par mois.',
    'home.acc_step1_title': 'Diagnostic & cartographie',
    'home.acc_step1_desc': 'On commence par comprendre. Cartographie des processus, identification des friction points, hiérarchisation par impact.',
    'home.acc_step2_title': 'Architecture des solutions',
    'home.acc_step2_desc': 'Sélection ou développement des outils adaptés. Sur mesure quand aucun existant ne convient.',
    'home.acc_step3_title': 'Déploiement & adoption',
    'home.acc_step3_desc': 'Mise en production, formation des équipes, ajustements. Le résultat compte — pas les slides.',
    'home.acc_step4_title': 'Suivi & optimisation',
    'home.acc_step4_desc': 'On mesure, on ajuste. Pas de mission qui se termine sur une livraison et disparaît.',

    // Conviction
    'home.conv_label': 'Notre conviction',
    'home.conv_title': 'Une petite équipe bien organisée peut',
    'home.conv_title_accent': 'rivaliser avec n\'importe qui.',
    'home.conv_quote': 'Chaque heure passée sur une tâche administrative, une relance manuelle ou un rapport qu\'on pourrait automatiser — c\'est une heure de moins sur ce qui crée vraiment de la valeur.',
    'home.conv_p1': 'Solutio existe pour que les professionnels puissent se concentrer sur ce qui leur rapporte — pas sur ce qui leur coûte. Pas les tâches redondantes, pas l\'administration, pas ce que n\'importe qui pourrait faire à leur place.',
    'home.conv_p2': 'L\'IA, l\'automatisation, les systèmes sur mesure ne sont plus réservés aux grands groupes. C\'est une infrastructure qui se démocratise — et ceux qui s\'en emparent maintenant prennent une longueur d\'avance qui ne se rattrape pas facilement.',
    'home.conv1_title': 'Pas de solution universelle',
    'home.conv1_desc': 'Chaque organisation a ses contraintes, son rythme, ses équipes. On part de là — pas d\'un template.',
    'home.conv2_title': 'La technologie comme moyen',
    'home.conv2_desc': 'L\'outil n\'est jamais la fin. Ce qui compte, c\'est ce qu\'il libère : du temps, de l\'attention, de la clarté.',
    'home.conv3_title': 'Qualité plutôt que quantité',
    'home.conv3_desc': 'Une petite équipe avec les bons systèmes bat une grande avec des process médiocres. On construit pour durer, pas pour faire du volume.',
    'home.conv4_title': 'Du concret, pas des slides',
    'home.conv4_desc': 'On ne livre pas des recommandations. On construit ce qui doit être construit, on reste jusqu\'à ce que ça marche.',

    // FAQ
    'home.faq_label': 'Questions fréquentes',
    'home.faq_title': 'Ce que vous vous demandez',
    'home.faq_title_accent': 'probablement.',
    'home.faq1_q': 'C\'est pour qui exactement ?',
    'home.faq1_a': 'On travaille avec des indépendants, des équipes de 5 personnes, et des structures de 50+. Ce qui compte ce n\'est pas la taille — c\'est l\'ambition de bien s\'organiser et la volonté de changer ce qui ne fonctionne pas.',
    'home.faq2_q': 'Quelle est la différence avec un consultant classique ?',
    'home.faq2_a': 'On ne repart pas avec un rapport. On reste jusqu\'à ce que la solution soit en production et adoptée par les équipes. Et quand c\'est pertinent, on construit les outils nous-mêmes plutôt que de recommander des licences.',
    'home.faq3_q': 'Combien de temps ça prend ?',
    'home.faq3_a': 'Le diagnostic initial prend quelques jours. La mise en œuvre dépend du périmètre — quelques semaines pour un système ciblé, quelques mois pour une transformation plus large. On définit ça ensemble avant de commencer.',
    'home.faq4_q': 'Est-ce qu\'on peut commencer petit ?',
    'home.faq4_a': 'Oui — et c\'est souvent le meilleur point d\'entrée. La cartographie gratuite permet déjà d\'identifier ce qui bloque le plus. Beaucoup de missions commencent par un problème précis avant de s\'élargir.',

    // Dual CTA
    'home.dcta_product_badge': 'Produit',
    'home.dcta_product_title': 'Vous voulez tester l\'outil ?',
    'home.dcta_product_sub': 'La cartographie est gratuite. 5 minutes, résultats immédiats. Aucun engagement.',
    'home.dcta_product_btn': 'Scanner mon organisation',
    'home.dcta_consult_badge': 'Accompagnement',
    'home.dcta_consult_title': 'Vous voulez aller plus loin ?',
    'home.dcta_consult_sub': 'On parle de votre organisation, vos besoins, ce qu\'on peut construire ensemble.',
    'home.dcta_consult_btn': 'Réserver un échange',

    // Index page translations
    'index.meta_title': 'Solutio — Conseil en transformation digitale & outils sur mesure',
    'index.meta_description': 'Diagnostic IA gratuit, cartographie organisationnelle, developpement d\'outils metier et accompagnement. Solutio aide les dirigeants a transformer leur entreprise.',
    'index.meta_keywords': 'transformation digitale, conseil, diagnostic, cartographie organisationnelle, outils sur mesure, PME',
    'index.structured_description': 'Cabinet de conseil en transformation digitale : diagnostic IA, outils sur mesure et accompagnement.',
    'index.hero_badge': 'Conseil & Transformation Digitale',
    'index.hero_title1': 'Votre entreprise peut faire ',
    'index.hero_title_highlight': 'beaucoup mieux',
    'index.hero_title2': 'On vous montre comment.',
    'index.hero_description': 'Diagnostic IA gratuit, cartographie de vos processus, construction d\'outils sur mesure et accompagnement concret. Un seul objectif : que votre organisation fonctionne vraiment.',
    'index.hero_cta_book': 'Reserver un echange',
    'index.hero_cta_tools': 'Decouvrir nos outils',
    'index.hero_trust_data': 'Donnees hebergees en Europe',
    'index.hero_trust_diag': 'Diagnostic gratuit sur 10 axes',
    'index.hero_trust_free': 'Sans engagement',
    'index.problem_label': 'Le constat',
    'index.problem_title': 'Vous le voyez tous les jours, mais vous n\'avez pas le temps de le mesurer',
    'index.problem_desc': 'Des processus qui ralentissent, des outils qui ne se parlent pas, des equipes qui compensent a la main. Le resultat : du temps perdu, de l\'energie gaspillee, et un potentiel sous-exploite.',
    'index.problem1_title': 'Des irritants invisibles',
    'index.problem1_desc': 'Les vrais blocages ne sont pas toujours la ou on les cherche. Sans cartographie, on traite les symptomes, pas les causes.',
    'index.problem2_title': 'Des outils empiles',
    'index.problem2_desc': 'Excel ici, un CRM la, Notion pour certains, emails pour le reste. Aucune vue consolidee, chaque equipe a son propre systeme.',
    'index.problem3_title': 'Des quick wins ignores',
    'index.problem3_desc': 'Des gains rapides (souvent quelques heures/semaine) existent dans toute organisation. Encore faut-il savoir ou regarder.',
    'index.services_label': 'Nos services',
    'index.services_title': 'Du diagnostic a la transformation, un seul interlocuteur',
    'index.services_desc': 'Pas de consulting theorique. On diagnostique, on construit, on accompagne — jusqu\'aux resultats.',
    'index.service1_title': 'Conseil & Diagnostic',
    'index.service1_subtitle': 'Comprendre avant d\'agir',
    'index.service1_desc': 'Audit complet de votre organisation : processus, outils, equipes, couts. On identifie ce qui freine votre croissance et on vous donne un plan d\'action concret.',
    'index.service1_feat1': 'Cartographie de vos processus et flux',
    'index.service1_feat2': 'Identification des goulots d\'etranglement',
    'index.service1_feat3': 'Analyse des couts caches et inefficacites',
    'index.service1_feat4': 'Plan d\'action priorise avec ROI estime',
    'index.service1_cta': 'Demander un diagnostic',
    'index.service2_title': 'Outils sur mesure',
    'index.service2_subtitle': 'Quand rien n\'existe sur le marche',
    'index.service2_desc': 'Developpement de plateformes et outils metier adaptes a vos besoins reels. Pas de SaaS generique : des solutions pensees pour votre facon de travailler.',
    'index.service2_feat1': 'Plateformes SaaS internes ou client',
    'index.service2_feat2': 'Automatisation de processus repetitifs',
    'index.service2_feat3': 'Integrations multi-outils (API, CRM, ERP)',
    'index.service2_feat4': 'Tableaux de bord et reporting sur mesure',
    'index.service2_cta': 'Discuter de votre projet',
    'index.service3_title': 'Accompagnement',
    'index.service3_subtitle': 'Du diagnostic a la transformation',
    'index.service3_desc': 'Suivi de la mise en oeuvre, formation de vos equipes, mesure des resultats. On reste a vos cotes jusqu\'a ce que les changements soient ancres.',
    'index.service3_feat1': 'Feuille de route sur 30/60/90 jours',
    'index.service3_feat2': 'Coaching equipes et conduite du changement',
    'index.service3_feat3': 'Suivi KPIs et ajustements',
    'index.service3_feat4': 'Transfert de competences',
    'index.service3_cta': 'Reserver un echange',
    'index.products_label': 'Nos produits',
    'index.products_title1': 'Des outils construits pour des vrais problemes. ',
    'index.products_title_highlight': 'Pas des features generiques.',
    'index.products_subtitle': 'Chaque produit nait d\'un manque identifie sur le terrain. La roadmap grandit avec les besoins.',
    'index.product_carto_badge': 'Disponible',
    'index.product_carto_title': 'Cartographie Orga',
    'index.product_carto_desc': 'Evaluez la maturite de vos processus, outils et equipes. Identifiez les irritants et generez un plan d\'optimisation actionnable.',
    'index.product_carto_feat1': 'Diagnostic gratuit en 10 packs',
    'index.product_carto_feat2': 'Radar de maturite par domaine',
    'index.product_carto_feat3': 'Quick wins immediats',
    'index.product_carto_feat4': 'Plan d\'action priorise par IA',
    'index.product_carto_cta': 'Decouvrir l\'outil',
    'index.product_lead_badge': 'Bientot',
    'index.product_lead_title': 'Lead Scraper',
    'index.product_lead_desc': 'Generation de leads ultra-cibles pour entrepreneurs, freelances et TPE. Trouvez vos cibles de niche sans les outils enterprise.',
    'index.product_lead_feat1': 'Scraping de sources pertinentes',
    'index.product_lead_feat2': 'Filtrage par criteres niche',
    'index.product_lead_feat3': 'Export propre et actionnable',
    'index.product_lead_feat4': 'Sans abonnement enterprise',
    'index.product_lead_cta': 'Rejoindre la liste d\'attente',
    'index.product_next_title': 'Prochain outil',
    'index.product_next_desc': 'En cours d\'identification. La roadmap est construite a partir des retours terrain et des besoins recurrents chez nos clients.',
    'index.product_next_text': 'Vous avez un besoin recurrent qu\'aucun outil ne couvre correctement ? On veut l\'entendre.',
    'index.product_next_cta': 'Partager un besoin',
    'index.cases_label': 'Developpement sur mesure',
    'index.cases_title1': 'Quand aucun outil existant ne correspond exactement ',
    'index.cases_title_highlight': 'a votre facon de travailler.',
    'index.cases_desc': 'On concoit et developpe des systemes applicatifs tailles pour votre organisation — pas un outil standard qu\'on vous demande d\'adapter. Architecture, integrations, interfaces : tout est pense pour vos equipes.',
    'index.case1_sector': 'Cabinet de conseil',
    'index.case1_tag1': 'Suivi de mission',
    'index.case1_tag2': 'Portail consultants',
    'index.case1_tag3': 'Reporting automatise',
    'index.case1_result': '5 outils metier + 1 plateforme de gestion',
    'index.case1_resultSub': 'au lieu d\'un pilotage 100% manuel',
    'index.case1_before': '25+ consultants, tout gere manuellement. Saisies redondantes, coordination dispersee, aucune vision consolidee. Le temps administratif l\'emportait sur le terrain.',
    'index.case1_after': 'Une plateforme sur mesure, 5 outils metier integres et une plateforme de gestion centralisee. Missions, activite, livrables — tout en un seul endroit. La structure tourne de facon autonome, sans intervention manuelle.',
    'index.case2_sector': 'Agence marketing d\'affiliation',
    'index.case2_tag1': 'SaaS Platform',
    'index.case2_tag2': 'Automation',
    'index.case2_tag3': 'Multi-clients',
    'index.case2_result': '-85%',
    'index.case2_resultSub': 'temps operationnel',
    'index.case2_before': 'Gestion manuelle de 6 clients d\'affiliation. Rapports hebdomadaires crees a la main dans Excel, extraction de donnees depuis 3 networks (Rakuten, Impact, Awin), briefs disperses entre emails et Google Docs. 20 heures par semaine uniquement sur le reporting.',
    'index.case2_after': 'Plateforme SaaS full-stack : import automatique multi-network, dashboard analytics temps reel, rapports hebdomadaires generes par IA chaque lundi, integration ClickUp. 3 heures par semaine au lieu de 20. Scalabilite de 6 a 50+ clients.',
    'index.cases_before_label': 'Situation initiale',
    'index.cases_after_label': 'Resultat',
    'index.conviction_label': 'Notre conviction',
    'index.conviction_title': 'La transformation digitale ne devrait pas etre un projet a 500K EUR qui echoue.',
    'index.conviction_p1': 'La plupart des entreprises n\'ont pas besoin d\'une "strategie digitale" de 200 pages. Elles ont besoin de comprendre ou elles perdent du temps, de l\'argent et de l\'energie — puis d\'agir sur les bonnes priorites.',
    'index.conviction_p2': 'C\'est ce qu\'on fait chez Solutio. On commence par un diagnostic concret (pas un audit de 3 mois), on identifie les quick wins (pas des recommandations vagues), et si besoin, on construit les outils qui manquent (pas du sur-engineering).',
    'index.conviction_quote': 'Notre objectif : que chaque euro investi dans votre transformation vous rapporte un resultat mesurable.',
    'index.faq_label': 'FAQ',
    'index.faq_title': 'Questions frequentes',
    'index.faq1_q': 'C\'est quoi exactement Solutio ?',
    'index.faq1_a': 'Solutio est un cabinet de conseil en transformation digitale. On aide les entreprises a comprendre ce qui freine leur croissance (diagnostic), a construire les outils qu\'il leur faut (developpement sur mesure), et a mettre en oeuvre les changements (accompagnement). Notre outil de cartographie organisationnelle est gratuit pour commencer.',
    'index.faq2_q': 'Le diagnostic est vraiment gratuit ?',
    'index.faq2_a': 'Oui. Le questionnaire complet (10 packs) est entierement gratuit. Vous obtenez une vue d\'ensemble, un radar de maturite et une carte interactive sans rien payer. Les analyses IA approfondies et le plan d\'action detaille sont disponibles a partir de 349 EUR.',
    'index.faq3_q': 'Combien coute un projet de developpement sur mesure ?',
    'index.faq3_a': 'Cela depend de la complexite. Un outil simple peut demarrer autour de quelques milliers d\'euros, une plateforme complete sera plus consequente. On commence toujours par un diagnostic gratuit pour cadrer le besoin avant de proposer un devis.',
    'index.faq4_q': 'Vous travaillez avec quels types d\'entreprises ?',
    'index.faq4_a': 'Principalement des PME et ETI de 10 a 500 collaborateurs, tous secteurs. Nos cas les plus frequents : cabinets de conseil, agences, entreprises industrielles, ESS. Le point commun : des dirigeants qui veulent transformer leur organisation sans se perdre.',
    'index.faq5_q': 'En quoi vous etes differents d\'un cabinet de conseil classique ?',
    'index.faq5_a': 'On ne fait pas de PowerPoint de 200 slides. On diagnostique avec un outil IA concret, on recommande des actions priorisees avec ROI estime, et si besoin on construit les outils. Du diagnostic a l\'implementation, un seul interlocuteur.',
    'index.faq6_q': 'Mes donnees sont-elles protegees ?',
    'index.faq6_a': 'Absolument. Vos donnees sont hebergees en Europe (Supabase Ireland), chiffrees en transit et au repos. Nous ne les partageons jamais avec des tiers. Vous pouvez supprimer vos donnees a tout moment.',
    'index.roi_label': 'Calculateur',
    'index.roi_title': 'Combien vous coutent vos inefficacites ?',
    'index.roi_subtitle': 'Estimation basee sur un cout horaire moyen de 45 EUR/h charges comprises.',
    'index.roi_team_label': 'Taille de l\'equipe',
    'index.roi_team_unit': 'personnes',
    'index.roi_hours_label': 'Heures perdues par personne/semaine',
    'index.roi_note': 'Ajustez les curseurs selon votre realite. La moyenne observee chez nos clients est de 4 a 8h/semaine de temps perdu par collaborateur.',
    'index.roi_cost_label': 'Cout estime des inefficacites',
    'index.roi_per_month': 'par mois',
    'index.roi_per_year': '/an',
    'index.roi_cta_note': 'Un diagnostic a 349 EUR peut identifier comment recuperer une partie significative de cette somme.',

    // Footer
    'footer.tagline': 'Conseil en transformation digitale et cartographie organisationnelle.',
    'footer.solutions': 'Services',
    'footer.support': 'Support',
    'footer.legal': 'Légal',
    'footer.legal_notice': 'Mentions légales',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'CGU',
    'footer.copyright': '© 2026 Solutio. Tous droits réservés.',

    // Not Found page
    'notfound.title': '404',
    'notfound.message': 'Oops ! Page introuvable',
    'notfound.back_home': 'Retour à l\'accueil',

    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.close': 'Fermer',
    'common.confirm': 'Confirmer'
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.diagnostic': 'Diagnostic',
    'nav.cartographie': 'Mapping',
    'nav.contact': 'Contact',
    'nav.start_diagnostic': 'Free scan',
    'nav.start_scan': 'Free scan',
    'nav.book_meeting': 'Book a meeting',
    'nav.conviction': 'Our belief',
    'nav.outils': 'Tools',
    'nav.realisations': 'Work',
    'nav.accompagnement': 'Consulting',

    // Hero section
    'hero.badge': 'Digital Transformation Consulting',
    'hero.title': 'Solutio | Digital transformation consulting & organizational mapping',
    'hero.h1_title': 'Transform your organization with AI',
    'hero.subtitle': 'Organizational mapping, AI analysis and tailored support',
    'hero.description': 'Solutio supports your digital transformation: free 3-minute scan, comprehensive process mapping and a concrete action plan to boost efficiency.',
    'hero.cta_diagnostic': 'Scan my organization',
    'hero.cta_scan': 'Scan my organization',
    'hero.cta_cartographie': 'Full mapping',
    'hero.cta_expert': 'Talk to an expert',
    'home.scan_free_3min': 'Free 3-min scan',

    // Trust indicators
    'home.free': 'Free',
    'home.minutes': '3 minutes',
    'home.no_commitment': 'No commitment',

    // Problem section
    'problem.title': 'The challenges of digital transformation',
    'problem.pain1': 'Your internal processes are opaque and hard to optimize',
    'problem.pain2': 'You waste time on low-value tasks',
    'problem.pain3': 'Your teams lack visibility on priorities',
    'problem.pain4': 'You don\'t know where to start your transformation',
    'problem.stat': '70% of digital transformation projects fail due to lack of prior diagnosis',
    'problem.stat_source': 'McKinsey Study 2024',
    'problem.transition': 'A structured diagnosis changes everything.',

    // Services section
    'services.title': 'Our services',
    'services.subtitle': 'Comprehensive support to succeed in your digital transformation',
    'services.diagnostic.title': 'AI Diagnostic',
    'services.diagnostic.description': 'Quick assessment of your digital maturity and identification of priority improvement areas.',
    'services.diagnostic.cta': 'Start diagnostic',
    'services.cartographie.title': 'Organizational Mapping',
    'services.cartographie.description': '10 analysis packs covering all your processes: HR, finance, sales, IT and more.',
    'services.cartographie.cta': 'Discover packs',
    'services.conseil.title': 'Strategic Consulting',
    'services.conseil.description': 'Personalized recommendations and concrete action plan for each identified transformation area.',
    'services.conseil.cta': 'Learn more',
    'services.accompagnement.title': 'Implementation Support',
    'services.accompagnement.description': 'Implementation follow-up, team training and long-term results measurement.',
    'services.accompagnement.cta': 'Contact us',

    // Method section
    'method.title': 'Our 3-step method',
    'method.subtitle': 'A structured approach to effectively transform your organization',
    'method.step1.title': 'Quick AI Diagnostic',
    'method.step1.description': '5 targeted questions to assess your digital maturity and identify your priorities. Free, no commitment.',
    'method.step2.title': 'Organizational Mapping',
    'method.step2.description': '10 in-depth analysis packs covering all areas of your organization, enhanced by AI.',
    'method.step3.title': 'Action plan & support',
    'method.step3.description': 'Concrete recommendations, prioritized roadmap and support through implementation.',

    // Proof section
    'proof.title': 'Why invest in digital transformation',
    'proof.stat1': '-30%',
    'proof.stat1_detail': 'operational costs through process optimization',
    'proof.stat1_source': 'McKinsey 2024',
    'proof.stat2': '+40%',
    'proof.stat2_detail': 'productivity with well-mapped processes',
    'proof.stat2_source': 'Forrester Research',
    'proof.stat3': '3x',
    'proof.stat3_detail': 'more likely to succeed with prior diagnosis',
    'proof.stat3_message': 'Start with the diagnostic',
    'proof.urgency': 'Every month without a clear diagnosis means misallocated time and resources',
    'proof.cta': 'Start my free diagnostic',

    // Benefits section
    'benefits.title': 'What Solutio brings you',
    'benefits.subtitle': 'A concrete and measurable approach to digital transformation.',
    'benefits.time.title': 'Immediate clarity',
    'benefits.time.description': 'In 5 minutes, get a clear picture of your digital maturity and priority areas.',
    'benefits.costs.title': 'Cost reduction',
    'benefits.costs.description': 'Identify processes to optimize first for quick financial impact.',
    'benefits.clarity.title': '360° view of your organization',
    'benefits.clarity.description': 'Mapping reveals interdependencies and transformation levers.',
    'benefits.expert.title': 'Expert support',
    'benefits.expert.description': 'A tailored action plan and follow-up to ensure concrete results.',

    // CTA section
    'home.cta_title': 'Ready to transform your organization?',
    'home.cta_subtitle': 'The diagnostic is free, results are immediate, impact is measurable.',
    'home.cta_additional': 'Start with a 5-minute AI diagnostic or explore our comprehensive organizational mapping.',
    'home.diagnostic_5min': 'Free diagnostic (5 min)',
    'home.expert_cta': 'Discover mapping',
    'home.solutions_count': 'companies supported',
    'home.satisfaction': 'client satisfaction',
    'home.response_time': 'to get your personalized diagnostic',

    // Testimonials
    'testimonial.1.quote': 'The diagnostic helped us prioritize our transformation projects. In 3 months, we saved 15h/week.',
    'testimonial.1.author': 'Marie D.',
    'testimonial.1.role': 'Operations Director',
    'testimonial.1.company': 'PME Services',
    'testimonial.2.quote': 'Organizational mapping revealed inefficiencies we didn\'t suspect. A real game-changer.',
    'testimonial.2.author': 'Thomas L.',
    'testimonial.2.role': 'CEO',
    'testimonial.2.company': 'TechStart',

    // Contact page
    'contact.title': 'Contact us',
    'contact.subtitle': 'Need support for your digital transformation? Our experts are here to guide you.',
    'contact.form_title': 'Send us a message',
    'contact.name_label': 'Full name *',
    'contact.name_placeholder': 'Your name',
    'contact.email_label': 'Email *',
    'contact.email_placeholder': 'your@email.com',
    'contact.company_label': 'Company',
    'contact.company_placeholder': 'Your company name',
    'contact.project_type_label': 'Project type',
    'contact.project_type_placeholder': 'Select...',
    'contact.project_type_brainstorm': 'Brainstorming session — Explore an idea or need',
    'contact.project_type_simple': 'Simple website or tool — Clear scope, fast delivery',
    'contact.project_type_big': 'Major project — Full system, multiple modules',
    'contact.project_type_other': 'Other — Not sure yet',
    'contact.message_label': 'Message *',
    'contact.message_placeholder': 'Describe your transformation need or project...',
    'contact.submit_button': 'Send message',
    'contact.success_title': 'Thank you for your message!',
    'contact.success_message': 'We have received your request and will respond as soon as possible.',
    'contact.send_another': 'Send another message',
    'contact.direct_contact_title': 'Direct contact',
    'contact.email_label_info': 'Email',
    'contact.phone_label': 'Phone',
    'contact.hours_label': 'Hours',
    'contact.hours_value': 'Mon-Fri, 9am-6pm',
    'contact.book_call_title': 'Book a call',
    'contact.book_call_subtitle': 'Schedule a 30-minute call with an expert to discuss your needs.',
    'contact.book_call_benefit1': 'Free process diagnostic',
    'contact.book_call_benefit2': 'Personalized recommendations',
    'contact.book_call_benefit3': 'Detailed action plan',
    'contact.book_call_button': 'Book now',
    'contact.faq_title': 'Frequently asked questions',
    'contact.faq_q1': 'How much does a diagnostic cost?',
    'contact.faq_a1': 'The online AI diagnostic is completely free. Personalized support is quoted on request.',
    'contact.faq_q2': 'How long to see results?',
    'contact.faq_a2': 'The diagnostic gives immediate results. First concrete gains appear within 4 to 8 weeks.',
    'contact.faq_q3': 'Do you support implementation?',
    'contact.faq_a3': 'Yes, we offer complete support: from strategy to execution.',

    // Diagnostic page (simplified 5-step version)
    'diagnostic.title': 'Digital Maturity Diagnostic',
    'diagnostic.subtitle': 'Answer 5 questions to assess your organization and receive personalized recommendations',
    'diagnostic.question_company_title': 'What is your company size?',
    'diagnostic.question_company_subtitle': 'Number of employees',
    'diagnostic.question_sector_title': 'What is your industry?',
    'diagnostic.question_sector_subtitle': 'Your main domain',
    'diagnostic.question_challenges_title': 'What are your main challenges?',
    'diagnostic.question_challenges_subtitle': 'Select or describe your current issues',
    'diagnostic.question_maturity_title': 'What is your current digitalization level?',
    'diagnostic.question_maturity_subtitle': 'Assess your current situation',
    'diagnostic.question_priorities_title': 'What are your transformation priorities?',
    'diagnostic.question_priorities_subtitle': 'What you want to improve first',

    'diagnostic.examples_company_1': '1-10 people',
    'diagnostic.examples_company_2': '11-50 people',
    'diagnostic.examples_company_3': '51-200 people',
    'diagnostic.examples_company_4': '200+ people',
    'diagnostic.examples_sector_1': 'Services',
    'diagnostic.examples_sector_2': 'Retail',
    'diagnostic.examples_sector_3': 'Manufacturing',
    'diagnostic.examples_sector_4': 'Tech / SaaS',
    'diagnostic.examples_sector_5': 'Healthcare',
    'diagnostic.examples_sector_6': 'Finance',
    'diagnostic.examples_challenges_1': 'Time-consuming manual processes',
    'diagnostic.examples_challenges_2': 'Lack of visibility / reporting',
    'diagnostic.examples_challenges_3': 'Inter-team communication',
    'diagnostic.examples_challenges_4': 'Disorganized document management',
    'diagnostic.examples_challenges_5': 'Disconnected tools',
    'diagnostic.examples_maturity_1': 'Very low digitalization (Excel, paper)',
    'diagnostic.examples_maturity_2': 'A few isolated tools',
    'diagnostic.examples_maturity_3': 'Connected but underused tools',
    'diagnostic.examples_maturity_4': 'Good digitalization, need to optimize',
    'diagnostic.examples_priorities_1': 'Automate repetitive tasks',
    'diagnostic.examples_priorities_2': 'Improve collaboration',
    'diagnostic.examples_priorities_3': 'Optimize business processes',
    'diagnostic.examples_priorities_4': 'Better data-driven decisions',
    'diagnostic.examples_priorities_5': 'Reduce operational costs',

    'diagnostic.examples_label': 'Options:',
    'diagnostic.step_label': 'Step',
    'diagnostic.progress_completed': 'completed',
    'diagnostic.question_number': 'Question',
    'diagnostic.previous_button': 'Previous',
    'diagnostic.next_button': 'Next',
    'diagnostic.see_recommendations': 'See my diagnostic',
    'diagnostic.results_title': 'Your digital maturity diagnostic',
    'diagnostic.results_subtitle': 'Here is your score and personalized recommendations',
    'diagnostic.maturity_score': 'Maturity Score',
    'diagnostic.potential_label': 'Potential',
    'diagnostic.time_saved_label': 'Estimated gain',
    'diagnostic.implementation_time': '4-8 weeks',
    'diagnostic.implementation_label': 'First results',
    'diagnostic.roi_label': 'Fast ROI',
    'diagnostic.roi_value': 'Measurable',
    'diagnostic.summary_title': 'Diagnostic summary',
    'diagnostic.company_size_caps': 'SIZE',
    'diagnostic.sector_label_caps': 'SECTOR',
    'diagnostic.challenges_caps': 'CHALLENGES',
    'diagnostic.maturity_caps': 'MATURITY',
    'diagnostic.recommendations_title': 'Our recommendations',
    'diagnostic.recommendations_subtitle': 'Priority actions for your organization',
    'diagnostic.cta_cartographie_title': 'Go further with mapping',
    'diagnostic.cta_cartographie_subtitle': 'Get a detailed analysis of each area of your organization with our 10 analysis packs.',
    'diagnostic.cta_cartographie_button': 'Discover mapping',
    'diagnostic.receive_email_title': 'Receive by email',
    'diagnostic.receive_email_subtitle': 'Get this diagnostic and our detailed recommendations',
    'diagnostic.send_report': 'Send report',
    'diagnostic.free_consultation_title': 'Free consultation',
    'diagnostic.free_consultation_subtitle': 'Talk with an expert to refine your strategy',
    'diagnostic.book_slot': 'Book a slot',
    'diagnostic.new_diagnostic': 'Redo diagnostic',

    // ── NEW HOMEPAGE ──
    // Hero
    'home.badge': 'Digital Transformation Consulting',
    'home.hero_line1': 'Your teams are excellent.',
    'home.hero_line2': 'Their environment should be too.',
    'home.hero_sub': 'Solutio exists so professionals can focus on what earns them money — not on what costs them.',
    'home.hero_btn_tools': 'See our tools',
    'home.hero_btn_work': 'Work with us',
    'home.hero_pill1': '2 tools in production',
    'home.hero_pill2': 'Custom-built systems',
    'home.hero_pill3': 'Consulting support',
    'home.hero_scroll': 'Scroll',

    // Outils
    'home.outils_label': 'Our products',
    'home.outils_title': 'Tools built for real problems.',
    'home.outils_title_accent': 'Not generic features.',
    'home.outils_sub': 'Every product is born from a gap identified in the field. The roadmap grows with actual needs.',
    'home.carto_title': 'Org Mapping',
    'home.carto_desc': 'Assess the maturity of your processes, tools and teams. Identify pain points and generate an actionable optimization plan.',
    'home.carto_f1': 'Free 5-minute scan',
    'home.carto_f2': 'Maturity radar by domain',
    'home.carto_f3': 'Immediate quick wins',
    'home.carto_f4': 'AI-prioritized action plan',
    'home.carto_btn': 'Scan my organization',
    'home.carto_badge': 'Available',
    'home.lead_title': 'Lead Scraper',
    'home.lead_desc': 'Ultra-targeted lead generation for entrepreneurs, freelancers and small businesses. Find your niche targets without enterprise tools.',
    'home.lead_f1': 'Scraping from relevant sources',
    'home.lead_f2': 'Niche-specific filtering',
    'home.lead_f3': 'Clean, actionable export',
    'home.lead_f4': 'No enterprise subscription',
    'home.lead_btn': 'Join the waitlist',
    'home.lead_badge': 'Coming soon',
    'home.next_title': 'Next tool',
    'home.next_desc': 'Currently being identified. The roadmap is built from field feedback and recurring client needs.',
    'home.next_sub': 'Have a recurring need that no tool covers properly? We want to hear it.',
    'home.next_btn': 'Share a need',

    // Réalisations
    'home.real_label': 'Custom development',
    'home.real_title': 'When no existing tool matches exactly',
    'home.real_title_accent': 'how you work.',
    'home.real_sub': 'We design and build application systems tailored to your organization — not a standard tool you\'re asked to adapt. Architecture, integrations, interfaces: everything is designed for your teams.',
    'home.real1_sector': 'Consulting firm',
    'home.real1_tag1': 'Mission tracking',
    'home.real1_tag2': 'Consultant portal',
    'home.real1_tag3': 'Automated reporting',
    'home.real1_metric': '5 business tools + 1 management platform',
    'home.real1_metric_label': 'instead of 6 separate tools',
    'home.real1_before': '25+ consultants, everything managed manually. Redundant data entry, scattered coordination, no consolidated view. Admin time outweighed fieldwork.',
    'home.real1_after': 'A custom-built platform, 5 integrated business tools and a centralized management platform. Missions, activity, deliverables — all in one place. The structure runs autonomously, without manual intervention.',
    'home.real2_sector': 'Affiliate marketing agency',
    'home.real2_tag1': 'SaaS Platform',
    'home.real2_tag2': 'Automation',
    'home.real2_tag3': 'Multi-client',
    'home.real2_metric': '-85%',
    'home.real2_metric_label': 'operational time',
    'home.real2_before': 'Manual management of 6 affiliate clients. Weekly reports built by hand in Excel, data pulled from 3 networks (Rakuten, Impact, Awin), briefs scattered across emails and Google Docs. 20 hours per week spent on reporting alone.',
    'home.real2_after': 'Full-stack SaaS platform: automatic multi-network import, real-time analytics dashboard, AI-generated weekly reports every Monday, ClickUp integration. 3 hours per week instead of 20. Scalability from 6 to 50+ clients.',
    'home.real_before_label': 'Initial situation',
    'home.real_after_label': 'Result',

    // Accompagnement
    'home.acc_label': 'Digital transformation',
    'home.acc_title': 'It\'s not just about tools.',
    'home.acc_title_accent': 'It\'s about how your organization actually works.',
    'home.acc_p1': 'Diagnose, prioritize, implement, train. We support SMBs from mapping their dysfunctions to deploying solutions in production.',
    'home.acc_p2': 'We intervene where it really hurts — not where it\'s comfortable to address. And we leave when it works, not when the mission is over on paper.',
    'home.acc_btn1': 'Talk about my project',
    'home.acc_btn2': 'Discover our tools',
    'home.acc_limit': 'Limited availability — a few companies per month.',
    'home.acc_step1_title': 'Diagnosis & mapping',
    'home.acc_step1_desc': 'We start by understanding. Process mapping, friction point identification, impact-based prioritization.',
    'home.acc_step2_title': 'Solution architecture',
    'home.acc_step2_desc': 'Selection or development of the right tools. Custom-built when nothing existing fits.',
    'home.acc_step3_title': 'Deployment & adoption',
    'home.acc_step3_desc': 'Production rollout, team training, adjustments. Results matter — not slides.',
    'home.acc_step4_title': 'Monitoring & optimization',
    'home.acc_step4_desc': 'We measure, we adjust. No mission that ends on delivery and disappears.',

    // Conviction
    'home.conv_label': 'Our belief',
    'home.conv_title': 'A small, well-organized team can',
    'home.conv_title_accent': 'compete with anyone.',
    'home.conv_quote': 'Every hour spent on an administrative task, a manual follow-up or a report that could be automated — is an hour less on what truly creates value.',
    'home.conv_p1': 'Solutio exists so professionals can focus on what earns them money — not what costs them. Not redundant tasks, not administration, not what anyone could do in their place.',
    'home.conv_p2': 'AI, automation, custom systems are no longer reserved for large corporations. It\'s infrastructure that\'s democratizing — and those who embrace it now gain a lead that\'s not easily caught up.',
    'home.conv1_title': 'No one-size-fits-all',
    'home.conv1_desc': 'Every organization has its constraints, its pace, its teams. We start from there — not from a template.',
    'home.conv2_title': 'Technology as a means',
    'home.conv2_desc': 'The tool is never the end. What matters is what it frees: time, attention, clarity.',
    'home.conv3_title': 'Quality over quantity',
    'home.conv3_desc': 'A small team with the right systems beats a large one with mediocre processes. We build to last, not to scale mindlessly.',
    'home.conv4_title': 'Concrete results, not slides',
    'home.conv4_desc': 'We don\'t deliver recommendations. We build what needs to be built, we stay until it works.',

    // FAQ
    'home.faq_label': 'Frequently asked questions',
    'home.faq_title': 'What you\'re',
    'home.faq_title_accent': 'probably wondering.',
    'home.faq1_q': 'Who is this for exactly?',
    'home.faq1_a': 'We work with freelancers, 5-person teams, and 50+ organizations. What matters isn\'t the size — it\'s the ambition to organize well and the willingness to change what doesn\'t work.',
    'home.faq2_q': 'How is this different from a traditional consultant?',
    'home.faq2_a': 'We don\'t leave with a report. We stay until the solution is in production and adopted by the teams. And when relevant, we build the tools ourselves rather than recommending licenses.',
    'home.faq3_q': 'How long does it take?',
    'home.faq3_a': 'The initial diagnosis takes a few days. Implementation depends on scope — a few weeks for a targeted system, a few months for a broader transformation. We define that together upfront.',
    'home.faq4_q': 'Can we start small?',
    'home.faq4_a': 'Yes — and it\'s often the best entry point. The free mapping already identifies what\'s blocking the most. Many missions start with a specific problem before expanding.',

    // Dual CTA
    'home.dcta_product_badge': 'Product',
    'home.dcta_product_title': 'Want to try the tool?',
    'home.dcta_product_sub': 'The mapping is free. 5 minutes, immediate results. No commitment.',
    'home.dcta_product_btn': 'Scan my organization',
    'home.dcta_consult_badge': 'Consulting',
    'home.dcta_consult_title': 'Want to go further?',
    'home.dcta_consult_sub': 'Let\'s talk about your organization, your needs, what we can build together.',
    'home.dcta_consult_btn': 'Book a call',

    // Index page translations
    'index.meta_title': 'Solutio — Digital transformation consulting & custom tools',
    'index.meta_description': 'Free AI diagnostic, organizational mapping, custom business tool development and hands-on support. Solutio helps business leaders transform their company.',
    'index.meta_keywords': 'digital transformation, consulting, diagnostic, organizational mapping, custom tools, SME',
    'index.structured_description': 'Digital transformation consulting firm: AI diagnostic, custom tools and hands-on support.',
    'index.hero_badge': 'Consulting & Digital Transformation',
    'index.hero_title1': 'Your business can do ',
    'index.hero_title_highlight': 'much better',
    'index.hero_title2': 'We show you how.',
    'index.hero_description': 'Free AI diagnostic, process mapping, custom tool development and hands-on support. One goal: making your organization truly work.',
    'index.hero_cta_book': 'Book a call',
    'index.hero_cta_tools': 'Discover our tools',
    'index.hero_trust_data': 'Data hosted in Europe',
    'index.hero_trust_diag': 'Free diagnostic across 10 axes',
    'index.hero_trust_free': 'No commitment',
    'index.problem_label': 'The reality',
    'index.problem_title': 'You see it every day, but you don\'t have time to measure it',
    'index.problem_desc': 'Processes slowing down, tools that don\'t talk to each other, teams compensating manually. The result: wasted time, wasted energy, and untapped potential.',
    'index.problem1_title': 'Invisible pain points',
    'index.problem1_desc': 'The real blockers aren\'t always where you expect. Without mapping, you treat symptoms, not root causes.',
    'index.problem2_title': 'Stacked tools',
    'index.problem2_desc': 'Excel here, a CRM there, Notion for some, emails for the rest. No consolidated view, each team has its own system.',
    'index.problem3_title': 'Ignored quick wins',
    'index.problem3_desc': 'Quick gains (often a few hours/week) exist in every organization. You just need to know where to look.',
    'index.services_label': 'Our services',
    'index.services_title': 'From diagnostic to transformation, a single point of contact',
    'index.services_desc': 'No theoretical consulting. We diagnose, build, and support — until results are delivered.',
    'index.service1_title': 'Consulting & Diagnostic',
    'index.service1_subtitle': 'Understand before acting',
    'index.service1_desc': 'Full audit of your organization: processes, tools, teams, costs. We identify what\'s holding back your growth and give you a concrete action plan.',
    'index.service1_feat1': 'Mapping of your processes and workflows',
    'index.service1_feat2': 'Identification of bottlenecks',
    'index.service1_feat3': 'Analysis of hidden costs and inefficiencies',
    'index.service1_feat4': 'Prioritized action plan with estimated ROI',
    'index.service1_cta': 'Request a diagnostic',
    'index.service2_title': 'Custom tools',
    'index.service2_subtitle': 'When nothing on the market fits',
    'index.service2_desc': 'Development of platforms and business tools tailored to your real needs. No generic SaaS: solutions designed for the way you work.',
    'index.service2_feat1': 'Internal or client-facing SaaS platforms',
    'index.service2_feat2': 'Automation of repetitive processes',
    'index.service2_feat3': 'Multi-tool integrations (API, CRM, ERP)',
    'index.service2_feat4': 'Custom dashboards and reporting',
    'index.service2_cta': 'Discuss your project',
    'index.service3_title': 'Support',
    'index.service3_subtitle': 'From diagnostic to transformation',
    'index.service3_desc': 'Implementation follow-up, team training, results measurement. We stay by your side until the changes are embedded.',
    'index.service3_feat1': '30/60/90-day roadmap',
    'index.service3_feat2': 'Team coaching and change management',
    'index.service3_feat3': 'KPI tracking and adjustments',
    'index.service3_feat4': 'Skills transfer',
    'index.service3_cta': 'Book a call',
    'index.products_label': 'Our products',
    'index.products_title1': 'Tools built for real problems. ',
    'index.products_title_highlight': 'Not generic features.',
    'index.products_subtitle': 'Every product is born from a gap identified in the field. The roadmap grows with actual needs.',
    'index.product_carto_badge': 'Available',
    'index.product_carto_title': 'Org Mapping',
    'index.product_carto_desc': 'Assess the maturity of your processes, tools and teams. Identify pain points and generate an actionable optimization plan.',
    'index.product_carto_feat1': 'Free diagnostic in 10 packs',
    'index.product_carto_feat2': 'Maturity radar by domain',
    'index.product_carto_feat3': 'Immediate quick wins',
    'index.product_carto_feat4': 'AI-prioritized action plan',
    'index.product_carto_cta': 'Discover the tool',
    'index.product_lead_badge': 'Coming soon',
    'index.product_lead_title': 'Lead Scraper',
    'index.product_lead_desc': 'Ultra-targeted lead generation for entrepreneurs, freelancers and small businesses. Find your niche targets without enterprise tools.',
    'index.product_lead_feat1': 'Scraping from relevant sources',
    'index.product_lead_feat2': 'Niche-specific filtering',
    'index.product_lead_feat3': 'Clean, actionable export',
    'index.product_lead_feat4': 'No enterprise subscription',
    'index.product_lead_cta': 'Join the waitlist',
    'index.product_next_title': 'Next tool',
    'index.product_next_desc': 'Currently being identified. The roadmap is built from field feedback and recurring client needs.',
    'index.product_next_text': 'Have a recurring need that no tool covers properly? We want to hear it.',
    'index.product_next_cta': 'Share a need',
    'index.cases_label': 'Custom development',
    'index.cases_title1': 'When no existing tool matches exactly ',
    'index.cases_title_highlight': 'the way you work.',
    'index.cases_desc': 'We design and develop application systems tailored to your organization — not a standard tool you\'re asked to adapt. Architecture, integrations, interfaces: everything is designed for your teams.',
    'index.case1_sector': 'Consulting firm',
    'index.case1_tag1': 'Mission tracking',
    'index.case1_tag2': 'Consultant portal',
    'index.case1_tag3': 'Automated reporting',
    'index.case1_result': '5 business tools + 1 management platform',
    'index.case1_resultSub': 'replacing 100% manual operations',
    'index.case1_before': '25+ consultants, everything managed manually. Redundant data entry, scattered coordination, no consolidated view. Admin time outweighed field work.',
    'index.case1_after': 'A custom platform, 5 integrated business tools and a centralized management platform. Missions, activity, deliverables — all in one place. The organization runs autonomously, without manual intervention.',
    'index.case2_sector': 'Affiliate marketing agency',
    'index.case2_tag1': 'SaaS Platform',
    'index.case2_tag2': 'Automation',
    'index.case2_tag3': 'Multi-client',
    'index.case2_result': '-85%',
    'index.case2_resultSub': 'operational time',
    'index.case2_before': 'Manual management of 6 affiliate clients. Weekly reports created by hand in Excel, data extraction from 3 networks (Rakuten, Impact, Awin), briefs scattered between emails and Google Docs. 20 hours per week on reporting alone.',
    'index.case2_after': 'Full-stack SaaS platform: automatic multi-network import, real-time analytics dashboard, AI-generated weekly reports every Monday, ClickUp integration. 3 hours per week instead of 20. Scalability from 6 to 50+ clients.',
    'index.cases_before_label': 'Starting situation',
    'index.cases_after_label': 'Result',
    'index.conviction_label': 'Our belief',
    'index.conviction_title': 'Digital transformation shouldn\'t be a 500K EUR project that fails.',
    'index.conviction_p1': 'Most companies don\'t need a 200-page "digital strategy". They need to understand where they\'re losing time, money and energy — then act on the right priorities.',
    'index.conviction_p2': 'That\'s what we do at Solutio. We start with a concrete diagnostic (not a 3-month audit), identify quick wins (not vague recommendations), and if needed, build the missing tools (no over-engineering).',
    'index.conviction_quote': 'Our goal: every euro invested in your transformation delivers a measurable result.',
    'index.faq_label': 'FAQ',
    'index.faq_title': 'Frequently asked questions',
    'index.faq1_q': 'What exactly is Solutio?',
    'index.faq1_a': 'Solutio is a digital transformation consulting firm. We help companies understand what\'s holding back their growth (diagnostic), build the tools they need (custom development), and implement changes (support). Our organizational mapping tool is free to start.',
    'index.faq2_q': 'Is the diagnostic really free?',
    'index.faq2_a': 'Yes. The full questionnaire (10 packs) is entirely free. You get an overview, a maturity radar and an interactive map without paying anything. In-depth AI analyses and detailed action plans are available from 349 EUR.',
    'index.faq3_q': 'How much does a custom development project cost?',
    'index.faq3_a': 'It depends on complexity. A simple tool can start at a few thousand euros, a full platform will be more substantial. We always start with a free diagnostic to scope the need before providing a quote.',
    'index.faq4_q': 'What types of companies do you work with?',
    'index.faq4_a': 'Mainly SMEs and mid-caps of 10 to 500 employees, all sectors. Our most common cases: consulting firms, agencies, industrial companies, social enterprises. The common thread: leaders who want to transform their organization without getting lost.',
    'index.faq5_q': 'How are you different from a traditional consulting firm?',
    'index.faq5_a': 'We don\'t do 200-slide PowerPoints. We diagnose with a concrete AI tool, recommend prioritized actions with estimated ROI, and if needed we build the tools. From diagnostic to implementation, a single point of contact.',
    'index.faq6_q': 'Is my data protected?',
    'index.faq6_a': 'Absolutely. Your data is hosted in Europe (Supabase Ireland), encrypted in transit and at rest. We never share it with third parties. You can delete your data at any time.',
    'index.roi_label': 'Calculator',
    'index.roi_title': 'How much are your inefficiencies costing you?',
    'index.roi_subtitle': 'Estimate based on an average hourly cost of 45 EUR/h fully loaded.',
    'index.roi_team_label': 'Team size',
    'index.roi_team_unit': 'people',
    'index.roi_hours_label': 'Hours lost per person/week',
    'index.roi_note': 'Adjust the sliders to your reality. The average we observe with our clients is 4 to 8h/week of wasted time per team member.',
    'index.roi_cost_label': 'Estimated cost of inefficiencies',
    'index.roi_per_month': 'per month',
    'index.roi_per_year': '/year',
    'index.roi_cta_note': 'A 349 EUR diagnostic can identify how to recover a significant portion of this amount.',

    // Footer
    'footer.tagline': 'Digital transformation consulting and organizational mapping.',
    'footer.solutions': 'Services',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.legal_notice': 'Legal notice',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.copyright': '© 2026 Solutio. All rights reserved.',

    // Not Found page
    'notfound.title': '404',
    'notfound.message': 'Oops! Page not found',
    'notfound.back_home': 'Return to Home',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.close': 'Close',
    'common.confirm': 'Confirm'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language][key] || key;

    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, params[param]);
      });
    }

    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
